###
GET http://localhost:8080/fornecedor/7
Content-Type: application/json

###
POST http://localhost:8080/fornecedor
Content-Type: application/json

{
  "uf": "SP",
  "itens": [
    {
      "nome": "Escova de dentes",
      "codigo": "0101010"
    }
  ]
}