

POST http://localhost:8081/pedido
Content-Type: application/json

{
    "endereco" : {
        "numero":"123",
        "logradouro" : "Teste",
        "uf": "SP"
    },
    "itensPedido": [
        {
            "produtoId": 1,
            "quantidade": 1
        }
    ]
}

###
GET http://localhost:8081/pedido/1
Content-Type: application/json
